### ISSUE TITLE
Request to fix a coding error in hakubooru/source.py

### ISSUE THREAD

**Issue by Koishi-Star** [KohakuBlueleaf/HakuBooru#3]
I'm trying to export images using hakubooru, but the export count is 0. After investigating, I found that on line 85 of hakubooru/source.py, the 'bucket_id' cannot pass the compilation check. 
![123](https://github.com/user-attachments/assets/ccd19595-3b1d-4282-9fe4-9e55e7038ccb)
I believe this is the reason for the export failure. I kindly request that you fix this bug. Thank you very much for your assistance.

**Comment by jxhxgt** [comment]
2024-07-29 21:51:06|[hakubooru]-INFO: Loading database
Database connected.
2024-07-29 21:51:06|[hakubooru]-INFO: Querying posts
2024-07-29 21:51:08|[hakubooru]-INFO: Found 5083 posts
2024-07-29 21:51:08|[hakubooru]-INFO: Building exporter
2024-07-29 21:51:08|[hakubooru]-INFO: Exporting images
reading buckets: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 992/992 [00:00<00:00, 798301.91it/s]
2024-07-29 21:51:08|[hakubooru]-WARNING: 992 buckets are not used because the bucket doesn't exist
2024-07-29 21:51:08|[hakubooru]-WARNING: 5083 posts are not found in the dataset
Some of them are gif or mp4 or corrupted files so small number is normal
Lot of not found can be caused by missing/outdating dataset files or corrupted dataset files
2024-07-29 21:51:08|[hakubooru]-INFO: Successfully exported 0 images
PS C:\Users\hjx43>

**Comment by jxhxgt** [comment]
> 我正在尝试使用 hakubooru 导出图像，但导出计数为 0。经过调查，我发现在 hakubooru/source.py 的第 85 行，“bucket_id”无法通过编译检查。 我认为这是导出失败的原因。我恳请您修复此错误。非常感谢您的帮助。 ![123](https://private-user-images.githubusercontent.com/66173435/352693495-ccd19595-3b1d-4282-9fe4-9e55e7038ccb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjE1MTgsIm5iZiI6MTcyMjI2MTIxOCwicGF0aCI6Ii82NjE3MzQzNS8zNTI2OTM0OTUtY2NkMTk1OTUtM2IxZC00MjgyLTlmZTQtOWU1NWU3MDM4Y2NiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEzNTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MTBkODUxMDgxNzM0ZmRiOGEwNGQ1ODczMTgzY2Q3ZmY1YjFiMTlhZTJkMDNhNTUwYTJkMzU0Nzc5ZDlkN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2NGRJuXczQY7ddtq0iXhjjxouKEajtZqlnLCJIgNymE)

help

**Comment by KohakuBlueleaf** [comment]
> > 我正在尝试使用 hakubooru 导出图像，但导出计数为 0。经过调查，我发现在 hakubooru/source.py 的第 85 行，“bucket_id”无法通过编译检查。 我认为这是导出失败的原因。我恳请您修复此错误。非常感谢您的帮助。 ![123](https://private-user-images.githubusercontent.com/66173435/352693495-ccd19595-3b1d-4282-9fe4-9e55e7038ccb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjE1MTgsIm5iZiI6MTcyMjI2MTIxOCwicGF0aCI6Ii82NjE3MzQzNS8zNTI2OTM0OTUtY2NkMTk1OTUtM2IxZC00MjgyLTlmZTQtOWU1NWU3MDM4Y2NiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEzNTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MTBkODUxMDgxNzM0ZmRiOGEwNGQ1ODczMTgzY2Q3ZmY1YjFiMTlhZTJkMDNhNTUwYTJkMzU0Nzc5ZDlkN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2NGRJuXczQY7ddtq0iXhjjxouKEajtZqlnLCJIgNymE)
> 
> help

Plz check the latest update on GitHub 
Try to install/clone it from github

**Comment by jxhxgt** [comment]
> > > 我正在尝试使用 hakubooru 导出图像，但导出计数为 0。经过调查，我发现在 hakubooru/source.py 的第 85 行，“bucket_id”无法通过编译检查。 我认为这是导出失败的原因。我恳请您修复此错误。非常感谢您的帮助。 ![123](https://private-user-images.githubusercontent.com/66173435/352693495-ccd19595-3b1d-4282-9fe4-9e55e7038ccb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjE1MTgsIm5iZiI6MTcyMjI2MTIxOCwicGF0aCI6Ii82NjE3MzQzNS8zNTI2OTM0OTUtY2NkMTk1OTUtM2IxZC00MjgyLTlmZTQtOWU1NWU3MDM4Y2NiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDEzNTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MTBkODUxMDgxNzM0ZmRiOGEwNGQ1ODczMTgzY2Q3ZmY1YjFiMTlhZTJkMDNhNTUwYTJkMzU0Nzc5ZDlkN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2NGRJuXczQY7ddtq0iXhjjxouKEajtZqlnLCJIgNymE)
> > 
> > 
> > help
> 
> Plz check the latest update on GitHub Try to install/clone it from github

你的python -m pip install hakubooru似乎没更新，从这下载的是有问题的，删掉之后用git的没问题了

**Comment by KohakuBlueleaf** [comment]
I said, install it from github.
